version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://localhost:6379
